# Generated by Django 4.1.3 on 2023-07-05 20:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_audiofile_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiofilechunk",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
